


export const planets = [
    {
        id: 'sun',
        name: 'Sun',
        texture: '/texture/sun-min.webp',
        description: 'Ngôi sao trung tâm của hệ mặt trời, cung cấp ánh sáng và năng lượng.',
        // NOTE: display radius is compressed for visualization; Sun must remain largest.
        // Increased so Sun appears prominently in the scene while keeping Earth = 1.
        radius: 12,
        distance: 0,
        speed: 0,
        isLightSource: true,
        hasAtmosphere: false,
    },
    {
        id: 'mercury',
        name: 'Mercury',
        texture: '/texture/mercury-min.webp',
        description: 'Hành tinh gần Mặt Trời nhất, nhỏ nhất trong hệ mặt trời.',
        radius: 0.38,
        distance: 15,
        speed: 0.04,
        hasAtmosphere: false,
    },
    {
        id: 'venus',
        name: 'Venus',
        texture: '/texture/venus-min.webp',
        description: 'Hành tinh giống Trái Đất nhưng có khí hậu cực kỳ khắc nghiệt.',
        radius: 0.95,
        distance: 20,
        speed: 0.035,
        hasAtmosphere: true,
        atmosphereColor: "#ffc46e",
    },
    {
        id: 'earth',
        name: 'Earth',
        texture: '/texture/Albedo-min.webp',
        description: 'Hành tinh xanh - nơi con người đang sinh sống.',
        radius: 1,
        distance: 28,
        speed: 0.03,
        hasAtmosphere: true,
        atmosphereColor: "#87ceeb",
    },
    {
        id: 'moon',
        name: 'Moon',
        texture: '/texture/moon-min.webp',
        description: 'Vệ tinh tự nhiên duy nhất của Trái Đất.',
        radius: 0.27,
        distance: 2.5,
        speed: 0.8,
        isMoon: true,
        hasAtmosphere: false,
    },
    {
        id: 'mars',
        name: 'Mars',
        texture: '/texture/mars-min.webp',
        description: 'Hành tinh đỏ, có thể là tương lai của nhân loại.',
        radius: 0.53,
        distance: 38,
        speed: 0.024,
        hasAtmosphere: true,
        atmosphereColor: "#c1440e",
    },
    {
        id: 'jupiter',
        name: 'Jupiter',
        texture: '/texture/jupiter-min.webp',
        description: 'Hành tinh khí khổng lồ với cơn bão Great Red Spot.',
        // Scaled down for visualization so it does not overshadow the Sun
        radius: 4.5,
        distance: 60,
        speed: 0.013,
        hasAtmosphere: true,
        atmosphereColor: "#bcaea1",
    },
    {
        id: 'saturn',
        name: "Saturn",
        // FIX: Sử dụng các biến đã import thay vì chuỗi ký tự
        texture: '/texture/Saturno-min.webp',
        ringTexture: '/texture/saturnringcolor-min.webp',
        ringAlphaMap: '/texture/saturn_ring_alpha-min.webp',
        description: 'Hành tinh với hệ thống vành đai nổi bật nhất.',
        // Slightly smaller than Jupiter in display scale
        radius: 4.0,
        distance: 100,
        speed: 0.009,
        hasAtmosphere: true,
        atmosphereColor: "#f0e68c",
    },
    {
        id: 'uranus',
        name: 'Uranus',
        texture: '/texture/Uranus-min.webp',
        description: 'Hành tinh nghiêng 98 độ, có màu xanh lam đặc trưng.',
        radius: 2.0,
        distance: 130,
        speed: 0.006,
        hasAtmosphere: true,
        atmosphereColor: "#aee5d8",
    },
    {
        id: 'neptune',
        name: 'Neptune',
        texture: '/texture/neptune-min.webp',
        description: 'Hành tinh xa nhất trong hệ mặt trời, với màu xanh đặc trưng.',
        radius: 1.8,
        distance: 160,
        speed: 0.005,
        hasAtmosphere: true,
        atmosphereColor: "#5b5ddf",
    },
];

export default planets;
